spring:
  application:
    name: vault-app

#  cloud:
#    vault:
#      host: localhost
#      port: 8200
#      scheme: http
#      uri: http://localhost:8200
#      token: 00000000-0000-0000-0000-000000000000